### ISSUE TITLE
SQL Table Performance Issue

### ISSUE THREAD

**Issue by yangjuns** [yash620/terrier#11]
1. After we merged in #10, even though the sql table seems to run faster when we need to convert between different projected rows, it runs slowers for common cases due to unnecessary copy assignments.
2. @jrolli suggested we should avoid malloc in header mangling.

**Comment by jrolli** [comment]
Do we still have performance concerns for this one after #16?

**Comment by jrolli** [comment]
Should we rework this benchmark to use `Scan` instead of `Select`?

**Comment by yangjuns** [comment]
This performance was improved but I am not sure if that's satisfying or not. 
![Screenshot from 2019-04-06 13-28-34](https://user-images.githubusercontent.com/14082358/55761400-2a3a4200-5a2d-11e9-8524-9471f65a748e.png)

**Comment by yangjuns** [comment]
Just opened an issue #22 . I will work on it.

**Comment by yashNaN** [comment]
Since this main issue has been addressed and you've opened a new one I'll go ahead and close this.
