### ISSUE TITLE
Add Update Benchmark

### ISSUE THREAD

**Issue by yangjuns** [yash620/terrier#12]
Update is the most expensive operation because it involves multiple memory allocations and copies if implemented naively.

**Comment by yangjuns** [comment]
- [x] SingelVersionUpdate

- [x] MultiVersionMatchUpdate

- [x] MultiVersionMismatchUpdate

**Comment by jrolli** [comment]
Are we good with the implementation for these benchmarks?

**Comment by yangjuns** [comment]
I think so. @yash620 reviewed it.
