### ISSUE TITLE
Projected Row/Column Header Mangling for Select/Scan

### ISSUE THREAD

**Issue by yashNaN** [yash620/terrier#4]
Modify header of the passed in projection so that there is no need for extra copies. Datatable directly fills in the projection

**Comment by jrolli** [comment]
Based off the PR for inverse column map (#5), we should make sure we clean up references to `BlockLayoutFromSchema` in the long run.  I will talk to Andy about the way forward and will probably create an issue on main after that discussion.

**Comment by jrolli** [comment]
Implemented in #10 and #16
