### ISSUE TITLE
Scans must begin on the latest version seen by transaction

### ISSUE THREAD

**Issue by yashNaN** [yash620/terrier#8]
If a transaction intermingles and update in between scans then whichever tuple is read is reinserted into the latest version's data table. If the latest version's datatable is not read first then all the tuples inserted into the latest version's data table will be read again. Therefore the scan would be returning some data twice. 

TOOD: Need to change how slot iterator works, and change the SqlTable::Begin and SqlTable::End so that Begin always gives some sentinel value that starts on the latest version.

**Comment by yangjuns** [comment]
I don't quite understand the issue. Do you mean another transaction updates the tuple or the same transaction? I thought Scan is one single operation and you could not stop the Scan and do an update and continue scan in a single transaction.

**Comment by jrolli** [comment]
The concern is that a query that is doing a scan in conjunction with updates.  The current `SqlTable::Scan` function returns a `ProjectedColumn` so there is no reason the optimizer couldn't take a vectorized approach to query execution ([MonetDB/X100 Paper](https://15721.courses.cs.cmu.edu/spring2019/papers/15-execution/boncz-cidr2005.pdf)).  If they took this approach and iterated on scan->process->update, we would need to ensure that updates did not incidentally insert tuples onto the end of the current scan.

**Comment by jrolli** [comment]
Addressed in PR #19.
